export default Object.freeze({
  LOGIN: "Login",
  MESSAGES: "Messages",
  SINGLE_MESSAGE: "SingleMessage",
  SIGNUP: "Sign up",
  POST_LISTING: "Post Listing",
  SEARCH_LOCATION: "Search Location",
  LISTING_DETAILS: "Listing Details",
  ACCOUNT_DETAILS: "Account Details",
  MY_LISTINGS: "My Listings",
  SELLER_LISTINGS: "Seller Listings",
  USER_SINGLE_LISTING: "User Single Listing Screen",
  SOLD_LISTINGS: "Sold Listing Screen",
  CHAT: "Chat",
  ALL_LISTINGS: 'All listings',
});
