export default Object.freeze({
  LOGIN: "Login",
  MESSAGES: "Messages",
  SINGLE_MESSAGE: "SingleMessage",
  SIGNUP: "Sign up",
  POST_LISTING: "Post Listing",
  SEARCH_LOCATION: "Search Location",
  LISTING_DETAILS: "Listing Details",
  ACCOUNT_DETAILS: "Account Details",
  MY_LISTINGS: "My Listings",
  SELLER_LISTINGS: "Seller Listings",
  USER_SINGLE_LISTING: "User Single Listing Screen",
  SOLD_LISTINGS: "Sold Listing Screen",
  CHAT: "Chat",
  ALL_LISTINGS: 'All listings',
  MY_ACCOUNT: 'My Account',
  FURNITURE: 'Furniture',
  CAR: 'Car',
  ELECTRONICS: 'Electronics',
  BOOKS: 'Books',
  CLOTHING: 'Clothing',
  SPORTS: 'Sports',
  ENTERTAINMENT: 'Entertainment',
  OTHERS: 'Others',
  HOME_SINGLE_LISTING: 'HomeSingleListing'
});
